### ISSUE TITLE
Duplicate search query gets issued by unrelated Axios request

### ISSUE THREAD

**Issue by JeroenAdam** [elastic/search-ui#1024] opened 2024-03-10 14:39 UTC
In my use case, I'm seeing SearchProvider issue a duplicate search query, triggered by an async XMLHttpRequest (Axios).
Those should not be related to eachother but they seem to be.

![image](https://github.com/elastic/search-ui/assets/16437621/6bbcfadc-ffb3-468a-8607-403457c025d0)

This gets triggered by a user interaction toggling/unfolding (by clicking) a result, I made it so that there is an API call to my application backend (not Elasticsearch).
The exit point from Axios is dispatchXhrRequest.
The entry point for SearchProvider is the useEffect dependent on config.searchQuery followed by an update of the searchQuery configuration in SearchDriver.
If I compare the previous response from Elasticsearch with the duplicate response, they are identitcal.

debug: true shows indeed 'Search UI: State Update' but there is no state update, there only was an Axios XMLHttpRequest.
As soon as I get rid of the XMLHttpRequest, the duplicate search query does not get issued.

![image](https://github.com/elastic/search-ui/assets/16437621/7903b27f-11a9-4999-b088-9b5d2ce8bbf7)

You can see this behavior live, go to the folllowing url and click on a result: https://login.adambahri.com:1112/realms/jhipster/protocol/openid-connect/auth?response_type=code&client_id=web_app&scope=openid%20profile%20email&redirect_uri=https://app.adambahri.com:1114/login&login_hint=user&password=cca86cd5b97b

Backend: Elasticsearch, packages: react-search-ui, search-ui-elasticsearch-connector

**Comment by joemcelroy** [comment] 2024-03-11 11:34
looking at your page, i noticed:
- that the SearchProvider component was being destroyed and re-created, firing a search for rendering, every time a click happened
- the url history stack was increasing for every result click

I suspect its re-rendering the page and that the clickhandler you have is adding a page in the history every time its being clicked. Check the way you handle the result click and prevent a url transition.

Closing this because I believe its not a bug in search-ui.

**Closed by joemcelroy** 2024-03-11 11:34 UTC
Labels: bug
