### ISSUE TITLE
I'd like for filters NOT to reset when search term changes

### ISSUE THREAD

**Issue by FokkeZB** [elastic/search-ui#292] opened 2019-06-27 10:53 UTC
Currently, when you change the search term - you'll lose all filters.

I'm not sure if that is a bug or a feature, but I find it annoying if you'd like to make your terms more specific to narrow down results. I'd like to at least have the option to keep the filters.

# Reproduce

1. Open https://search-ui-stable.netlify.com/?q=Death&size=n_20_n&filters%5B0%5D%5Bfield%5D=states&filters%5B0%5D%5Bvalues%5D%5B0%5D=California&filters%5B0%5D%5Btype%5D=any
2. Notice the filter on _California_
3. Change the search term to _Yosemite_
4. Notice the filter is gone

**Comment by JasonStoltz** [comment] 2019-06-27 10:58
@FokkeZB That is as designed, as this is typical of *most* search experiences. I have an issue in the backlog about providing an option to make filters "sticky", so that they do not get reset. Does this makes sense to you? https://github.com/elastic/search-ui/issues/89

I'm going to close this issue for now, let's move the discussion to #89.

**Closed by JasonStoltz** 2019-06-27 10:58 UTC

**Comment by johanarnor** [comment] 2019-10-31 07:30
For those who find this issue and think that it hasn't been implemented yet (like me) - check the [docs](https://github.com/elastic/search-ui/blob/master/ADVANCED.md#searchbox)! It's been implemented since https://github.com/elastic/search-ui/pull/391

**Comment by JasonStoltz** [comment] 2019-10-31 11:27
Good point @johanarnor, thanks!
