### ISSUE TITLE
How to implement infinite scroll in react

### ISSUE THREAD

**Issue by PradeepGorule14** [elastic/search-ui#577] opened 2021-07-22 06:11 UTC
Hi I'm new in Elastic search and I'm trying to implement infinite scroll on the front end side I check every where but get no satisfactory answer and i have no idea how to implement it so could you please help me for this

`
import React, { useEffect, useState } from "react";

import AppSearchAPIConnector from "@elastic/search-ui-app-search-connector";
import ResultView from "./ResultView";
import {
  ErrorBoundary,
  Facet,
  SearchProvider,
  SearchBox,
  Results,
  PagingInfo,
  ResultsPerPage,
  Paging,
  Sorting,
  WithSearch,
} from "@elastic/react-search-ui";
import { Layout } from "@elastic/react-search-ui-views";
import "@elastic/react-search-ui-views/lib/styles/styles.css";
import "./Result.scss";
import {
  buildAutocompleteQueryConfig,
  buildFacetConfigFromConfig,
  buildSearchOptionsFromConfig,
  buildSortOptionsFromConfig,
  getConfig,
  getFacetFields,
} from "./config/config-helper";
import { Container, Row, Col } from "reactstrap";
import SideBar from "./SideBar";
const { hostIdentifier, searchKey, endpointBase, engineName } = getConfig();
const connector = new AppSearchAPIConnector({
  searchKey,
  engineName,
  hostIdentifier,
  endpointBase,
});

export default function App() {
  const [total, setTotal] = useState(50);
  const config = {
    searchQuery: {
      facets: buildFacetConfigFromConfig(),
      ...buildSearchOptionsFromConfig(),
    },
    autocompleteQuery: buildAutocompleteQueryConfig(),
    apiConnector: connector,
    alwaysSearchOnInitialLoad: true,
    initialState: {
      resultsPerPage: 30,
    },
    setResultsPerPage: total,
  };
  const [pageConfig, setPageConfig] = useState(config);

  useEffect(() => {
    document.addEventListener("scroll", () => {
      let scrollTop = document.documentElement.scrollTop,
        windowHeight = window.innerHeight,
        height = document.body.scrollHeight - windowHeight,
        scrollPercentage = scrollTop / height;

      if (scrollPercentage == 1) {
        setTotal(total + 10);

        config.initialState.resultsPerPage = total + 10;

        setPageConfig(config);
      }
    });
  }, [total, pageConfig]);

  return (
    <SearchProvider config={pageConfig}>
      {console.log(pageConfig, "page")}
      <WithSearch mapContextToProps={({ wasSearched }) => ({ wasSearched })}>
        {({ wasSearched }) => {
          return (
            <div className="App">
              <ErrorBoundary>
                <Layout
                  header={<SearchBox autocompleteSuggestions={true} />}
                  className="es-result"
                  sideContent={
                    <div>
                      {wasSearched && (
                        <>
                          <SideBar
                            label={"Sort by"}
                            sortOptions={buildSortOptionsFromConfig()}
                          >
                            <div className="accordion" id="accordionExample">
                              <div className="accordion-item">
                                <h2
                                  className="accordion-header"
                                  id="headingOne"
                                >
                                  <button
                                    className="accordion-button"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse0"
                                    aria-expanded="true"
                                    aria-controls="collapseOne"
                                  >
                                    Sort by
                                  </button>
                                </h2>
                                <div
                                  id="collapse0"
                                  className="accordion-collapse collapse show"
                                  aria-labelledby="heading0"
                                  data-bs-parent="#accordionExample"
                                >
                                  <Sorting
                                    sortOptions={buildSortOptionsFromConfig()}
                                  />
                                </div>
                              </div>
                            </div>
                          </SideBar>
                        </>
                      )}
                    </div>
                  }
                  bodyContent={
                    <>
                      <Results
                        resultView={ResultView}
                        className="row"
                        shouldTrackClickThrough={true}
                      />
                    </>
                  }
                  bodyHeader={
                    <React.Fragment>
                      {/* {wasSearched && <PagingInfo />} 
                      {wasSearched && <ResultsPerPage />}  */}
                    </React.Fragment>
                  }
                  // bodyFooter={<Paging />}
                />
              </ErrorBoundary>
            </div>
          );
        }}
      </WithSearch>
    </SearchProvider>
  );
}

`

As you can see in the code I'm updating the size of resultPerpage value using hooks but it is not working because in browser URL it shows the size in the query parameter like below

`http://localhost:3000/?size=n_60_n`

**Comment by JasonStoltz** [comment] 2021-07-22 13:58
There's not a great way to do it right now. See this thread for some discussion around this feature: https://gitter.im/elastic-search-ui/community?at=60a5dba202556214c0d8ea95

Closing as a duplicate of https://github.com/elastic/search-ui/issues/560

**Closed by JasonStoltz** 2021-07-22 13:58 UTC
